### ISSUE TITLE
.NET 6 Improvements MegaThread

### ISSUE THREAD

**Issue by RehanSaeed** [Dotnet-Boxed/Templates#973]
- [x] Update the target framework for your app to `net6.0` and update packages to `6.0.0`.
- [ ] [Fix nullable reference type annotation errors](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-1/#nullable-reference-type-annotations)
- [x] Look into simplifying API template using Mi.cro API's. How does this work with Swashbuckle?
- [x] Add HTTP/3 support
- [x] [dotnet watch now does dotnet watch run by default.](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-1/#dotnet-watch-now-does-dotnet-watch-run-by-default)
- [x] Enable [hot reload](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-3/#initial-net-hot-reload-support).

```
{
  "profiles": {
    "dotnet": {
      "commandName": "Project",
      "hotReloadProfile": "aspnetcore"
    }
  }
}
```

- [x] Add `dotnetRunMessages` to `launchSettings.json` https://github.com/dotnet/sdk/issues/14656.
- [x] Switch to `DateOnly` and `TimeOnly` structs https://github.com/dotnet/runtime/issues/49036.
- [x] Use `TryGetNonEnumeratedCount` for `Boxed.Mapping` https://github.com/dotnet/core/issues/6098#issuecomment-825157960.
- [x] Use `LoggerMessageAttribute` for [faster logging performance](https://devblogs.microsoft.com/dotnet/announcing-net-6-preview-4/#microsoft-extensions-logging-compile-time-source-generator) https://github.com/dotnet/runtime/issues/45290.
- [x] Use `ValidateOnStart` to validate configuration options on startup https://github.com/dotnet/runtime/issues/36391.
- [x] Use new `app.Use` overload https://github.com/dotnet/aspnetcore/pull/31784.
- [x] Use new API's to [get HTTP headers](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-5/#faster-get-and-set-for-http-headers).
- [x] Use [`CreateAsyncScope` instead of `CreateScope`](https://devblogs.microsoft.com/dotnet/announcing-net-6-preview-5/#dependency-injection-createasyncscope-apis).
- [ ] Add [Open Telemetry Metrics](https://devblogs.microsoft.com/dotnet/announcing-net-6-preview-5/#libraries-support-for-opentelemetry-metrics).
- [ ] Consider use of `<AnalysisMode>AllEnabledByDefault</AnalysisMode>`.
- [x] Use [IHttpActivityFeature](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-6/#ihttpactivityfeature) to get the current `Activity`.
- [x] Add [System.Text.Json Source Generators](https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-source-generator/#mvc-webapis-signalr-houdini).
- [x] Call [configuration.GetRequiredSection("Foo")](https://twitter.com/davidfowl/status/1422816521051459591?s=20).
- [x] Use `ArgumentNullException.ThrowIfNull(foo)`.
- [x] Use new minimal hosting and [`ConfigurationManager` API](https://andrewlock.net/exploring-dotnet-6-part-1-looking-inside-configurationmanager-in-dotnet-6/) for quicker startup.
- [x] [Developer exception page is now registered for you](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-rc-1/#developer-exception-page-middleware-change).
- [x] Add [embedded README](https://devblogs.microsoft.com/nuget/add-a-readme-to-your-nuget-package/) in NuGet package.
- [x] Use `readonly record` instead of `record`.
- [x] Search for potential const interpolated string usages e.g. `static readonly Foo = $"{a}{b}"` can be rewritten as const Foo = $"{a}{b}" if both `a` and `b` are constants.

**Comment by VictorioBerra** [comment]
Regarding Micro APIS https://github.com/dotnet/aspnetcore/issues/27724

The goal of them seems to be to simplify the boilerplate to make the code more approachable to beginners. 

The power of Boxed Templates is that it comes easy to customize and it shows the best practices right out of the box (pun intended). So, if when Micro APIs come out if they lack model binding, validation, filters or any other important features I think we should wait.

They did say:

> Improve the endpoint routing APIs to the point that we could make it the default API story in ASP.NET Core

If that ends up being true, and we see support from Swashbuckle, I think that will make it a more compelling argument to move that direction.

**Comment by RehanSaeed** [comment]
Agreed, lets see what they do.
